Repository WildCodeSchool-2024-09/js-toulouse-origins-digital, pull requests merged in 2025-01, with the labels that each got.

#2 S1 us05/create homepage
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/CarouselPrimary.tsx
  client/src/components/CarouselVideo.tsx
  client/src/pages/HomePage.tsx
  client/src/styles/CarouselPrimary.css
  client/src/styles/CarouselVideo.css
  client/src/styles/HomePage.css
  package-lock.json
Labels: REVIEWD

#4 S1 us10/website navigation interface
  client/src/assets/images/add.png
  client/src/assets/images/bookmark.png
  client/src/assets/images/close.png
  client/src/assets/images/controller.svg
  client/src/assets/images/home-2.png
  client/src/assets/images/magnifying-glass.png
  client/src/assets/images/search.png
  client/src/assets/images/user-solid.svg
  client/src/assets/images/white-magnifying-glass.svg
  client/src/assets/images/write.png
  client/src/components/CarrouselAuto.tsx
  client/src/components/Header.tsx
  client/src/components/NavBar.tsx
  client/src/components/SearchBar.tsx
  client/src/pages/HomeScreen.tsx
  client/src/styles/CarouselPrimary.css
  client/src/styles/CarrouselAuto.css
  client/src/styles/Header.css
  client/src/styles/NavBar.css
  client/src/styles/SearchBar.css
Labels: REVIEWD

#5 feat: schema sql
  client/src/styles/CarouselVideo.css
  client/src/styles/NavBar.css
  server/database/schema.sql
Labels: CORRECTIONS_DONE

#7 S1 us02/user login signup components
  client/src/components/UserLogin.tsx
  client/src/pages/HomePage.tsx
  client/src/styles/UserLogin.css
Labels: REVIEWD

#9 S1 us04/fix modallogin
  client/src/App.tsx
  client/src/components/CarrouselAuto.tsx
  client/src/components/NavBar.tsx
  client/src/components/UserLogin.tsx
  client/src/contexts/NavProvider.tsx
  client/src/main.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/HomeScreen.tsx
  client/src/pages/Search.tsx
  client/src/types/interface.ts
Labels: REVIEWD

#11 S2 us22/create bread table category
  client/src/App.css
  client/src/assets/images/bg-img-cateory.png
  client/src/components/CarouselPrimary.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/HomeScreen.tsx
  client/src/styles/CarouselPrimary.css
  client/src/styles/HomePage.css
  client/src/styles/HomeScreen.css
  client/src/styles/NavBar.css
  server/database/schema.sql
  server/src/modules/category/categoryActions.ts
  server/src/modules/category/categoryRepository.ts
  server/src/router.ts
Labels: REVIEWD

#12 feat: create table video Bread
  server/src/modules/video/videoActions.ts
  server/src/modules/video/videoRepository.ts
  server/src/router.ts
Labels: REVIEWD

#14 S2 us22/create back playlist
  README.md
  server/database/fixtures/ItemSeeder.ts
  server/src/modules/favorite/favoriteActions.ts
  server/src/modules/favorite/favoriteRepository.ts
  server/src/modules/item/itemActions.ts
  server/src/modules/item/itemRepository.ts
  server/src/modules/playlists/playlistsActions.ts
  server/src/modules/playlists/playlistsRepository.ts
  server/src/modules/videoplaylist/videoPlaylistActions.ts
  server/src/modules/videoplaylist/videoPlaylistRepository.ts
  server/src/router.ts
  server/tests/item/routes.spec.ts
Labels: CORRECTIONS_DONE, REVIEWD

#15 S2 us22/user table
  client/index.html
  client/src/assets/images/favicon.svg
  client/src/components/NavBar.tsx
  server/database/schema.sql
  server/package.json
  server/src/modules/user/userActions.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
Labels: REVIEWD

#16 refactor: merge Login and SignUp components into one file with useState
  client/src/components/UserLogin.tsx
  client/src/components/UserSignUp.tsx
  client/src/styles/UserLogin.css
  client/src/styles/UserSignUp.css
Labels: REVIEWD

#17 feat: create read, add, remove for video category table
  client/src/assets/images/admin-management.png
  client/src/assets/images/bookmark.png
  client/src/assets/images/category-management.png
  client/src/assets/images/modify.png
  client/src/assets/images/pencil-management.png
  client/src/assets/images/shield-avatar.png
  client/src/assets/images/trash-management.png
  client/src/assets/images/users-management.png
  client/src/assets/images/video-management.png
  client/src/styles/HomePage.css
  server/src/modules/videocategory/videoCategoryActions.ts
  server/src/modules/videocategory/videoCategoryRepository.ts
  server/src/router.ts
Labels: CONFLICTS_RESOLVED, REVIEWD

#19 S3 us24/display videos home page
  client/src/App.css
  client/src/assets/images/swap.png
  client/src/assets/images/upload-image.png
  client/src/components/CarouselPrimary.tsx
  client/src/components/CarouselVideo.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/HomeScreen.tsx
  client/src/pages/Search.tsx
  client/src/pages/Video.tsx
  client/src/styles/CarouselPrimary.css
  client/src/styles/CarouselVideo.css
  client/src/styles/HomePage.css
  client/src/styles/HomeScreen.css
  server/database/schema.sql
  server/src/modules/videocategory/videoCategoryActions.ts
  server/src/modules/videocategory/videoCategoryRepository.ts
  server/src/router.ts
Labels: REVIEWD

#20 S3 us15/create page playlists
  client/src/App.css
  client/src/assets/images/supprimer.png
  client/src/components/NavBar.tsx
  client/src/components/PlaylistList.tsx
  client/src/components/VideosGrid.tsx
  client/src/main.tsx
  client/src/pages/Playlists.tsx
  client/src/services/playlistService.ts
  client/src/styles/Playlists.css
  client/src/types/types.ts
  server/database/schema.sql
  server/src/app.ts
  server/src/modules/playlists/playlistsActions.ts
  server/src/modules/video/videoActions.ts
  server/src/modules/videoPlaylist/videoAndPlaylistActions.ts
  server/src/modules/videoPlaylist/videoAndPlaylistRepository.ts
  server/src/router.ts
Labels: REVIEWD

#22 S2 us22/user table
  client/src/App.tsx
  client/src/components/NavBar.tsx
  client/src/components/UserLogin.tsx
  client/src/components/UserLogout.tsx
  client/src/contexts/NavProvider.tsx
  client/src/main.tsx
  package-lock.json
  server/database/schema.sql
  server/src/modules/auth/authActions.ts
  server/src/modules/user/userActions.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
  server/src/types/express/index.d.ts
Labels: REVIEWD

#24 feat: create search-logic
  client/package.json
  client/src/components/SearchBar.tsx
  client/src/components/VideosGrid.tsx
  client/src/styles/SearchBar.css
  client/src/styles/VideoCard.css
  package-lock.json
  server/package.json
  server/src/modules/video/videoActions.ts
  server/src/modules/video/videoRepository.ts
  server/src/router.ts
Labels: CORRECTIONS_DONE, REVIEWD

#25 fix: local-storage
  client/src/App.tsx
  client/src/components/NavBar.tsx
  client/src/components/UserLogin.tsx
  client/src/components/VideoCard.tsx
  client/src/pages/Playlists.tsx
  client/src/styles/VideoCard.css
  server/src/modules/video/videoActions.ts
  server/src/modules/video/videoRepository.ts
  server/src/router.ts
Labels: REVIEWD

#26 S4 us25/user profil
  client/.env.sample
  client/src/App.tsx
  client/src/components/UserLogin.tsx
  client/src/components/UserLogout.tsx
  client/src/styles/NavBar.css
  client/src/styles/UserLogin.css
  client/src/styles/UserLogout.css
  package-lock.json
  server/.gitignore
  server/package.json
  server/src/app.ts
  server/src/modules/auth/authActions.ts
  server/src/router.ts
Labels: CORRECTIONS_DONE, REVIEWD

#28 S4 us03/manage data on admin view
  client/package.json
  client/src/components/AdminModal.tsx
  client/src/components/CardCategoryManager.tsx
  client/src/components/CardUserManager.tsx
  client/src/components/CardVideoManager.tsx
  client/src/components/NavBar.tsx
  client/src/pages/Admin.tsx
  client/src/services/deleteCategory.ts
  client/src/services/deleteUser.ts
  client/src/services/deleteVideo.ts
  client/src/services/useModal.ts
  client/src/styles/Admin.css
  client/src/styles/AdminModal.css
  client/src/styles/NavBar.css
  package-lock.json
  server/database/schema.sql
  server/src/modules/user/userRepository.ts
Labels: REVIEWD
