Repository WildCodeSchool-2024-09/js-toulouse-origins-digital, pull requests merged in 2025-02, with the labels that each got.

#29 S4 us03/manage data on admin view
  client/src/App.css
  client/src/components/CardUserManager.tsx
  client/src/components/CardVideoManager.tsx
  client/src/components/CarouselPrimary.tsx
  client/src/components/CarouselVideo.tsx
  client/src/components/ModalCategoryManager.tsx
  client/src/components/ModalUserManager.tsx
  client/src/components/ModalVideoManager.tsx
  client/src/components/SearchBar.tsx
  client/src/components/VideoCard.tsx
  client/src/components/VideosGrid.tsx
  client/src/pages/Admin.tsx
  client/src/pages/HomePage.tsx
  client/src/services/useModal.ts
  client/src/styles/CardUserManager.css
  client/src/styles/CarouselVideo.css
  client/src/styles/ModalManager.css
  client/src/styles/VideoCard.css
  server/database/schema.sql
  server/src/modules/auth/authActions.ts
  server/src/modules/category/categoryRepository.ts
  server/src/modules/user/userActions.ts
  server/src/modules/user/userRepository.ts
  server/src/modules/video/videoActions.ts
  server/src/modules/video/videoRepository.ts
  server/src/router.ts
Labels: CHANGE_REQUESTED, REVIEWD

#30 S4 us03/manage data on admin view
  client/package.json
  client/src/components/CardCategoryManager.tsx
  client/src/components/CardUserManager.tsx
  client/src/components/ModalCategoryManager.tsx
  client/src/components/ModalUserManager.tsx
  client/src/pages/Admin.tsx
  client/src/services/uploadService.ts
  client/src/styles/ModalManager.css
  client/tsconfig.json
  package-lock.json
  server/.env.sample
  server/database/schema.sql
  server/package.json
  server/services/cloudinaryConfig.ts
  server/src/modules/upload/uploadActions.ts
  server/src/router.ts
Labels: REVIEWD

#31 S3 us11/create favorite page
  client/src/App.tsx
  client/src/components/CarouselVideo.tsx
  client/src/components/CarousselFavoriteVideo.tsx
  client/src/components/NavBar.tsx
  client/src/components/VideoCard.tsx
  client/src/contexts/FavoritesContext.tsx
  client/src/main.tsx
  client/src/pages/Favorite.tsx
  client/src/styles/CarousselFavoriteVideo.css
  client/src/styles/Favorite.css
  client/src/styles/VideoCard.css
Labels: REVIEWD

#34 fix: user connexion navbar
  client/src/App.tsx
  client/src/components/NavBar.tsx
  client/src/components/UserLogout.tsx
  server/src/modules/auth/authActions.ts
Labels: REVIEWD

#35 S5 us03/manage data on admin view
  client/src/components/CardCategoryManager.tsx
  client/src/components/CardUserManager.tsx
  client/src/components/ModalCategoryManager.tsx
  client/src/components/ModalVideoManager.tsx
  client/src/pages/Admin.tsx
  client/src/styles/CardUserManager.css
  client/src/styles/CardVideoManager.css
  client/src/styles/UserModal.css
  server/database/schema.sql
  server/src/modules/user/userRepository.ts
  server/src/modules/video/videoActions.ts
  server/src/modules/video/videoRepository.ts
  server/src/router.ts
Labels: REVIEWD

#37 S3 us11/create favorite page
  client/src/components/CarousselFavoriteVideo.tsx
  client/src/components/VideoCard.tsx
  client/src/contexts/FavoritesContext.tsx
  client/src/pages/Favorite.tsx
  client/src/styles/Favorite.css
Labels: CONFLICTS, CONFLICTS_RESOLVED, REVIEWD

#38 S5 us03/manage data on admin view
  client/src/components/ModalCategoryManager.tsx
  client/src/components/ModalUserManager.tsx
  client/src/components/ModalVideoManager.tsx
  client/src/pages/Admin.tsx
  server/src/modules/user/userActions.ts
  server/src/router.ts
Labels: REVIEWD

#39 fix: make image change functionnal with cloudinary
  client/src/App.tsx
  client/src/components/NavBar.tsx
  client/src/components/UserProfileSettings.tsx
  client/src/pages/Playlists.tsx
  client/src/services/uploadService.ts
  client/src/styles/NavBar.css
  server/src/modules/auth/authActions.ts
  server/src/router.ts
Labels: REVIEWD

#41 feat: fetch category from back-end for favorite page
  client/src/components/VideoCard.tsx
  client/src/pages/Favorite.tsx
  server/src/app.ts
Labels: REVIEWD

#42 feat: close button user modal
  client/.gitignore
  client/src/components/NavBar.tsx
  client/src/components/UserModal.tsx
  client/src/components/VideoCard.tsx
  client/src/contexts/NavProvider.tsx
  client/src/styles/NavBar.css
Labels: REVIEWD

#43 feat: create alert window
  client/src/components/AlertModal.tsx
  client/src/components/ModalCategoryManager.tsx
  client/src/components/ModalUserManager.tsx
  client/src/components/ModalVideoManager.tsx
  client/src/services/useModal.ts
  client/src/styles/AlertModal.css
  server/src/router.ts
Labels: REVIEWD

#45 S6 us11/create favorite page
  client/src/components/SettingFavoriteVideo.tsx
  client/src/components/VideoCard.tsx
  client/src/pages/Favorite.tsx
  client/src/services/favoriteService.ts
  client/src/styles/Favorite.css
  client/src/styles/SettingFavoriteVideo.css
  server/src/modules/favorite/favoriteActions.ts
  server/src/modules/favorite/favoriteRepository.ts
  server/src/router.ts
Labels: CHANGE_REQUESTED, CORRECTIONS_DONE, REVIEWD

#46 feat: add fetch to read data on favorites page
  client/src/App.tsx
  client/src/components/SettingFavoriteVideo.tsx
  client/src/components/VideoCard.tsx
  client/src/contexts/FavoritesContext.tsx
  client/src/pages/Favorite.tsx
  client/src/services/favoriteService.ts
  client/src/styles/NavBar.css
  client/src/styles/VideoCard.css
  server/database/schema.sql
  server/src/modules/favorite/favoriteActions.ts
  server/src/router.ts
Labels: REVIEWD

#48 feat: add confirm modal
  client/src/components/CardCategoryManager.tsx
  client/src/components/CardUserManager.tsx
  client/src/components/CardVideoManager.tsx
  client/src/components/ConfirmModal.tsx
  client/src/components/ModalCategoryManager.tsx
  client/src/components/ModalUserManager.tsx
  client/src/components/ModalVideoManager.tsx
  client/src/components/UserModal.tsx
  client/src/components/VideoCard.tsx
  client/src/services/useModal.ts
  client/src/styles/ConfirmModal.css
  client/src/styles/UserModal.css
Labels: REVIEWD

#47 S6 us08/video access
  client/src/components/VideoCard.tsx
  client/src/pages/Favorite.tsx
  client/src/pages/HomeScreen.tsx
  server/src/router.ts
Labels: REVIEWD

#49 style: change close button for video card
  client/src/components/SearchBar.tsx
  client/src/components/VideoCard.tsx
  client/src/styles/VideoCard.css
Labels: REVIEWD

#50 feat: modal login and user with transparent behind
  client/src/components/UserLogin.tsx
  client/src/styles/UserLogin.css
  client/src/styles/UserModal.css
Labels: REVIEWD

#51 S6 us12/final design
  client/src/components/PlaylistList.tsx
  client/src/components/SettingFavoriteVideo.tsx
  client/src/components/VideosGrid.tsx
  client/src/pages/Playlists.tsx
  client/src/styles/App.css
  client/src/styles/Playlists.css
  client/src/styles/SettingFavoriteVideo.css
Labels: REVIEWD

#52 style: updated styles for Favorites, Playlist, and Search pages
  client/src/styles/Playlists.css
  client/src/styles/SearchBar.css
  client/src/styles/SettingFavoriteVideo.css
Labels: REVIEWD

#53 S7 us12/final design
  client/src/components/CarouselPrimary.tsx
  client/src/components/CarrouselAuto.tsx
  client/src/components/ModalCategoryManager.tsx
  client/src/components/ModalUserManager.tsx
  client/src/components/VideoCard.tsx
  client/src/contexts/NavProvider.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/HomeScreen.tsx
  client/src/styles/CarouselPrimary.css
  client/src/styles/CarrouselAuto.css
  client/src/styles/HomePage.css
  client/src/styles/HomeScreen.css
Labels: REVIEWD

#54 S6 us12/final design
  client/src/components/Header.tsx
  client/src/components/NavBar.tsx
  client/src/styles/Admin.css
  client/src/styles/CardVideoManager.css
  client/src/styles/Header.css
  client/src/styles/NavBar.css
  client/src/styles/Playlists.css
  client/src/styles/UserModal.css
Labels: REVIEWD

#55 S7 us12/final design
  client/src/App.css
  client/src/components/VideoCard.tsx
  client/src/styles/ConfirmModal.css
  client/src/styles/VideoCard.css
Labels: REVIEWD

#57 fix: correct favorite icon
  client/src/components/VideoCard.tsx
Labels: REVIEWD

#58 S7 us12/final design
  client/package.json
  client/src/App.css
  client/src/components/CarouselVideo.tsx
  client/src/components/SearchBar.tsx
  client/src/components/UserLogout.tsx
  client/src/pages/Admin.tsx
  client/src/pages/HomeScreen.tsx
  client/src/styles/HomeScreen.css
  client/src/styles/SearchBar.css
  client/src/styles/UserModal.css
  package-lock.json
Labels: REVIEWD

#59 S6 us12/final design
  client/src/components/NavBar.tsx
  client/src/components/SettingFavoriteVideo.tsx
  client/src/styles/Favorite.css
  client/src/styles/Playlists.css
  client/src/styles/SettingFavoriteVideo.css
Labels: REVIEWD

#60 S7 us12/final design
  client/src/App.css
  client/src/App.tsx
  client/src/components/SearchBar.tsx
  client/src/components/UserLogin.tsx
  client/src/components/UserLogout.tsx
  client/src/components/VideoCard.tsx
  client/src/pages/AccessDenied.tsx
  client/src/pages/HomePage.tsx
  client/src/pages/HomeScreen.tsx
  client/src/pages/Playlists.tsx
  client/src/styles/AccessDenied.css
  client/src/styles/AlertModal.css
  client/src/styles/Favorite.css
  client/src/styles/Header.css
  client/src/styles/HomePage.css
  client/src/styles/ModalManager.css
  client/src/styles/NavBar.css
  client/src/styles/Playlists.css
  client/src/styles/SearchBar.css
  client/src/styles/UserLogin.css
  client/src/styles/VideoCard.css
Labels: REVIEWD

#61 fix: correct create video on admin view
  client/src/pages/Admin.tsx
Labels: REVIEWD
